# Generated by Django 3.1.4 on 2020-12-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'elves',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('elf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staff.elf')),
                ('country', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'couriers',
            },
            bases=('staff.elf',),
        ),
        migrations.CreateModel(
            name='Craftsman',
            fields=[
                ('elf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staff.elf')),
                ('craft', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'craftsmen',
            },
            bases=('staff.elf',),
        ),
    ]
