# Generated by Django 3.1.4 on 2020-12-13 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.UUIDField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'children',
                'managed': True,
            },
        ),
    ]
