# Generated by Django 3.1.4 on 2020-12-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('sender_id', models.UUIDField()),
                ('country', models.TextField()),
                ('address', models.TextField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'letters',
                'managed': False,
            },
        ),
    ]
